### ISSUE TITLE
New Release v0.11.0

### ISSUE THREAD

**Issue by rajathchain** [mpugach/docker_omnicored#13]
Hi! Will a new docker image be released for the latest Omni version v0.11.0?
https://github.com/OmniLayer/omnicore/releases/tag/v0.11.0

@mpugach @um1st

**Comment by mpugach** [comment]
Hi @rajathchain 

Thanks for the update. I do not work with Omni anymore

But I do spend some effort to accept the PRs and to update images on Docker Hub.

so PRs are welcome :hugs:

**Comment by um1st** [comment]
Hi @rajathchain 
PR in on the process

**Comment by mpugach** [comment]
Thank you @um1st 

the tags are pushed to Docker Hub

**Comment by rajathchain** [comment]
Thankyou @mpugach and @um1st !!
