### ISSUE TITLE
Can't access with curl

### ISSUE THREAD

**Issue by proactive-dev** [mpugach/docker_omnicored#6]
@mpugach @cnjack @nerddan @Kayuii 
OS: ubuntu 18.04 (AWS Instance)
Used docker omnicore version: v0.6.0
Run command: 
`docker run --rm --name omnicored -v /home/ubuntu/.omnicore:/omnicore/data -p 8442:8332 -it mpugach/omnicored -server -txindex -rpcuser=rpcuser -rpcpassword=rpcpasswd -rpcbind=0.0.0.0:8332`
And I requested this.
`curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockcount","params":[]}' -H 'content-type:text/plain;' http://rpcuser:rpcpasswd@172.31.5.5:8442/`
(172.31.5.5 is AWS private IP.)
But I got the following response.
I want your kind help.
Regards.

**Comment by mpugach** [comment]
Hi @Apollo-IT, will you provide the response which you mentioned?

**Comment by proactive-dev** [comment]
@mpugach Thanks for your replies. I've fixed the above issue. But facing a new issue.
Omnicore stops automatically when it is fully synced.
Do you have any experience with that issue?

**Comment by mpugach** [comment]
unfortunately, I did not face it

**Comment by proactive-dev** [comment]
Thanks for your replies.

**Comment by developer1-belfrics** [comment]
> @mpugach @cnjack @nerddan @Kayuii
> OS: ubuntu 18.04 (AWS Instance)
> Used docker omnicore version: v0.6.0
> Run command:
> `docker run --rm --name omnicored -v /home/ubuntu/.omnicore:/omnicore/data -p 8442:8332 -it mpugach/omnicored -server -txindex -rpcuser=rpcuser -rpcpassword=rpcpasswd -rpcbind=0.0.0.0:8332`
> And I requested this.
> `curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockcount","params":[]}' -H 'content-type:text/plain;' http://rpcuser:rpcpasswd@172.31.5.5:8442/`
> (172.31.5.5 is AWS private IP.)
> But I got the following response.
> I want your kind help.
> Regards.

I have tried like this curl cmd I did not get any response. Kindly share me any example
